# Generated by Django 5.1.7 on 2025-04-21 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=20, verbose_name='客戶名稱')),
                ('client_gui', models.CharField(max_length=8, verbose_name='客戶統編')),
                ('client_phone', models.CharField(max_length=10, verbose_name='聯絡電話')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60, verbose_name='施工品項')),
                ('product_price', models.IntegerField(verbose_name='單價')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_address', models.CharField(max_length=60, verbose_name='施作地址')),
                ('order_status', models.CharField(default='未啟動', max_length=10, verbose_name='訂單狀態')),
                ('order_date', models.DateField(verbose_name='訂單日期')),
                ('order_amount', models.IntegerField(blank=True, verbose_name='總金額(已稅)')),
                ('contact_name', models.CharField(blank=True, max_length=10, verbose_name='聯絡人姓名')),
                ('contact_phone', models.CharField(blank=True, max_length=10, verbose_name='聯絡人電話')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimates.client')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='數量')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimates.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimates.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='estimates.OrderProduct', to='estimates.product'),
        ),
    ]
