# Generated by Django 5.1.7 on 2025-05-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0003_change_client_col_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='created_date',
        ),
        # cancel order_amount
        migrations.RemoveField(
            model_name='order',
            name='order_amount'
        ),
        # new tax_tate
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(max_digits=5, decimal_places=2, default=5.00)
        ),
    ]
