# Generated by Django 5.1.7 on 2025-05-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0007_quotation_number_quotation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='number',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='報價單編號'),
        ),
    ]
