# Generated by Django 5.1.7 on 2025-05-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0008_alter_quotation_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='面積'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='工作名稱'),
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True, verbose_name='訂單編號'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=100, verbose_name='施作地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='聯絡人姓名'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', '未處理'), ('processing', '處理中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=9),
        ),
    ]
