# Generated by Django 5.1.7 on 2025-05-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0009_remove_order_contact_phone_order_area_order_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='訂單編號'),
        ),
    ]
