# Generated by Django 5.1.7 on 2026-01-14 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_image_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='subtitle',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='公告', max_length=20)),
                ('type', models.CharField(default='primary', max_length=40)),
                ('context', models.TextField(null=True)),
                ('pdf_path', models.CharField(max_length=100, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.service')),
            ],
        ),
    ]
