# Generated by Django 5.1.7 on 2025-12-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='address',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
