# Generated by Django 5.1.7 on 2026-01-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_instance_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('icon', models.CharField(max_length=50)),
                ('icon_color', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('subnussuibTimeDesc', models.TextField()),
                ('signatureDesc', models.TextField()),
                ('scopeOfSurveyDesc', models.TextField()),
            ],
        ),
    ]
