# Generated by Django 5.1.7 on 2026-01-14 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_image_alter_service_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pages.service'),
            preserve_default=False,
        ),
    ]
