# Generated by Django 5.1.7 on 2026-05-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_image_image_path_alter_image_subtitle_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='scopeOfSurveyDesc',
            field=models.TextField(blank=True, null=True, verbose_name='簽證'),
        ),
        migrations.AlterField(
            model_name='service',
            name='signatureDesc',
            field=models.TextField(blank=True, null=True, verbose_name='調查範圍'),
        ),
        migrations.AlterField(
            model_name='service',
            name='subnussuibTimeDesc',
            field=models.TextField(blank=True, null=True, verbose_name='提送時機'),
        ),
    ]
