# Generated by Django 5.1.7 on 2025-05-17 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0002_remove_quotation_amount_quotation_tax_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_gui',
            new_name='gui',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_phone',
            new_name='phone',
        ),
    ]
