# Generated by Django 5.1.7 on 2025-05-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0004_change_col_name_of_product_and_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': '業主', 'verbose_name_plural': '業主管理'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '訂單', 'verbose_name_plural': '訂單'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '工作項目', 'verbose_name_plural': '工作項目'},
        ),
        migrations.AlterModelOptions(
            name='quotation',
            options={'verbose_name': '報價單', 'verbose_name_plural': '報價單'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='啟用狀態'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='訂單日期'),
        ),
    ]
