# Generated by Django 5.1.7 on 2025-05-29 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0005_alter_client_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gui',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='客戶統編'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='聯絡電話'),
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='子工作項目')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproducts', to='estimates.product')),
            ],
        ),
    ]
