# Generated by Django 5.1.7 on 2025-05-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0006_alter_client_gui_alter_client_phone_subproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='number',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True, verbose_name='報價單編號'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'None'), ('draft', '草稿'), ('sent', '已報價'), ('accepted', '已接受'), ('rejected', '已拒絕')], default='', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='面積'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='contact_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='聯絡人姓名'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='訂單日期'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='施作名稱'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='tax_rate',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=9),
        ),
    ]
