# Generated by Django 5.1.7 on 2026-02-04 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0013_alter_quotation_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='tamp',
            new_name='stamp',
        ),
    ]
