# Generated by Django 5.1.7 on 2026-02-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0010_alter_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='公司名稱')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='傳真')),
                ('tax_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='統編')),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('tamp', models.CharField(blank=True, max_length=255, null=True)),
                ('engineer_display', models.BooleanField(default=True)),
            ],
        ),
    ]
