# Generated by Django 5.1.7 on 2026-02-04 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0011_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '公司', 'verbose_name_plural': '公司管理'},
        ),
        migrations.AddField(
            model_name='quotation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotations.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='engineer_display',
            field=models.BooleanField(default=True, verbose_name='技師顯示'),
        ),
    ]
