# Generated by Django 5.1.7 on 2026-02-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0016_alter_order_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='模板指示'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='模板指示'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='施作地址'),
        ),
    ]
