# Generated by Django 5.1.7 on 2026-02-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0017_product_is_template_quotation_is_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(max_length=40, verbose_name='公司名稱'),
        ),
    ]
