# Generated by Django 5.1.7 on 2026-02-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0018_alter_company_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='icon',
            field=models.CharField(blank=True, default='quotations/assets/img/台整LOGO.png', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='stamp',
            field=models.CharField(blank=True, default='quotations/assets/img/台整stamp.png', max_length=255, null=True),
        ),
    ]
