# Generated by Django 5.1.7 on 2026-02-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0019_alter_company_icon_alter_company_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='icon',
            field=models.CharField(blank=True, default='quotations/assets/img/台整logo.png', max_length=255, null=True),
        ),
    ]
