# Generated by Django 5.1.7 on 2026-02-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0020_alter_company_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='contact_name',
        ),
        migrations.AddField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='聯絡人姓名'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='聯絡人電話'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='聯絡電話'),
        ),
    ]
