# Generated by Django 5.1.7 on 2026-02-24 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0021_remove_quotation_contact_name_client_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='工作項目類型')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
            ],
            options={
                'verbose_name': '工作項目類型',
                'verbose_name_plural': '工作項目類型',
            },
        ),
        migrations.CreateModel(
            name='WorkTypeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='數量')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.product')),
                ('worktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.worktype')),
            ],
        ),
        migrations.AddField(
            model_name='worktype',
            name='products',
            field=models.ManyToManyField(through='quotations.WorkTypeProduct', to='quotations.product'),
        ),
    ]
