# Generated by Django 5.1.7 on 2026-02-24 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0022_worktype_worktypeproduct_worktype_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktype',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quotations.client'),
        ),
        migrations.AddField(
            model_name='worktype',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quotations.company'),
        ),
    ]
