# Generated by Django 5.1.7 on 2026-02-25 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0023_worktype_client_worktype_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='is_template',
        ),
        migrations.AlterField(
            model_name='worktype',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quotations.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worktype',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quotations.company'),
            preserve_default=False,
        ),
    ]
