# Generated by Django 5.1.7 on 2026-03-06 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0024_remove_product_is_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotations.worktype'),
        ),
    ]
